drop table djkombu_queue cascade;
drop table djkombu_message cascade;
drop table celery_tasksetmeta cascade;
drop table djcelery_intervalschedule cascade;
drop table djcelery_crontabschedule cascade;
drop table djcelery_periodictasks cascade;
drop table djcelery_periodictask cascade;
drop table djcelery_workerstate cascade;
drop table djcelery_taskstate cascade;
